### PR TITLE
Fix indentation in XML/XSD files

### LINKED ISSUE #899: "Auto indent" setting is broken in version 0.25.0
Hello!

Unfortunately, after my update to version 0.25.0, "auto indent" setting was broken for XML and XSD files (even with value "full" there is no indentation after pressing Enter). In version 0.24.0 this rule is working fine.

Here're some of my tech parameters (if you need more, please, tag me in comments below):
- OS: Windows 10 Home Edition 22H2 (19045.2846)
- VS Code: 1.77.3

### PR DESCRIPTION
**Pull request by datho7561**
Make sure to upcast `string|DocumentFilter` correctly when setting indentation rules.

Fixes #899

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -37,8 +35,13 @@ export async function activate(context: ExtensionContext): Promise<XMLExtensionA
   registerClientOnlyCommands(context);
 
   // Update indentation rules for all language which are XML.
-  XML_SUPPORTED_LANGUAGE_IDS.forEach(l => {
-    const languageId = <string> l;
+  XML_SUPPORTED_LANGUAGE_IDS.forEach((l: string | DocumentFilter) => {
```
Comment (angelozerr) [inline src/extension.ts:38]: I think you can use  `DocumentSelector` which is `string | DocumentFilter`

**Comment by angelozerr** [comment]
See my comment otherwise it LGTM

@JessicaJHee if you have time could you test the PR of @datho7561 and merge it if it is good to have a prerlease tomorrow please.

**Review by JessicaJHee — APPROVED** [review]
I've tested this PR and fixes the issue as expected. Once Angelo's comment is addressed, I think this is good to go! Thanks for providing a fix so quickly!

**Comment by angelozerr** [comment]
Thanks so much @datho7561 !

**Comment by angelozerr** [comment]
Thanks @JessicaJHee for your fast review
