### PR TITLE
Fix alpine lemminx server

### LINKED ISSUE #1015: lemminx-alpine server not found
the alpine version is present
image

but the extension is looking for the linux one
```
[Error - 11:49:40 AM] XML Support client: couldn't create connection to server.
Launching server using command /home/vscode/.vscode-server-insiders/extensions/redhat.vscode-xml-0.27.2024053103-alpine-x64/server/lemminx-linux failed. Error: spawn /home/vscode/.vscode-server-insiders/extensions/redhat.vscode-xml-0.27.2024053103-alpine-x64/server/lemminx-linux ENOENT
```

### PR DESCRIPTION
**Pull request by cirolosapio**
fixes #1015

### CODE REVIEW

File: src/server/binary/binaryServerStarter.ts [hunk 1]
```diff
@@ -206,13 +206,32 @@ function getBinaryEnvironment(): any {
...
 
+/**
+ * Returns the platform of the current operating system.
+ * If the OS is Alpine Linux, it returns 'alpine'.
+ * Otherwise, it returns the platform string provided by the 'os' module.
+ *
+ * @returns The platform of the current operating system.
+ */
+function getPlatform (): ReturnType<typeof os.platform> | 'alpine' {
+  if (fs.existsSync('/etc/os-release')) {
```
Comment (rgrunber) [inline src/server/binary/binaryServerStarter.ts:217]: Would it be sufficient to just use the presence of `/etc/alpine-release` ? to return `alpine` ? I'd like to keep this as minimal as possible without any reading.

File: src/server/binary/binaryServerStarter.ts [hunk 2]
```diff
@@ -206,13 +206,32 @@ function getBinaryEnvironment(): any {
...
 }
 
+/**
+ * Returns the platform of the current operating system.
+ * If the OS is Alpine Linux, it returns 'alpine'.
+ * Otherwise, it returns the platform string provided by the 'os' module.
+ *
+ * @returns The platform of the current operating system.
+ */
+function getPlatform (): ReturnType<typeof os.platform> | 'alpine' {
```
Comment (rgrunber) [inline src/server/binary/binaryServerStarter.ts:216]: Could this be `: NodeJS.Platform | 'alpine'` or do you feel it's more correct to reference the method itself since that's what is really being called ?

File: src/server/binary/binaryServerStarter.ts (hunk 1 above)
Comment (cirolosapio) [reply src/server/binary/binaryServerStarter.ts]: thanks, I didn't know that file exists. updated

**Review by rgrunber — APPROVED** [review]

**Comment by cirolosapio** [comment]
hi @rgrunber is there an ETA when this bugfix will be released ?

**Comment by cirolosapio** [comment]
i use devcontainer and the extensions list are defined in the `devcontainer.json` file and it is not possible to specify the pre-release version, so it's never installed

**Comment by datho7561** [comment]
Supposedly: https://github.com/microsoft/vscode/issues/149383#issuecomment-1132192731
